# Generated by Django 4.2.5 on 2023-09-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('favorite_type', models.CharField(max_length=20)),
                ('owned_pokemons', models.ManyToManyField(to='pokemons.pokemon')),
            ],
        ),
    ]
