# Generated by Django 4.2.5 on 2023-10-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0010_alter_pokemon_catched_at'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='owned_pokemons',
            field=models.ManyToManyField(blank=True, to='pokemons.pokemon'),
        ),
    ]
