# Generated by Django 4.2.5 on 2023-10-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='master',
            field=models.CharField(blank=True, default='Available', max_length=150),
        ),
    ]
