# Generated by Django 4.2.5 on 2023-10-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='master',
            field=models.CharField(max_length=150),
        ),
    ]
