# Generated by Django 4.2.5 on 2023-10-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_alter_gym_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='master',
            field=models.CharField(blank=True, default='Available', max_length=150),
        ),
    ]
