# Generated by Django 4.2.5 on 2023-09-26 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=30)),
                ('attack', models.IntegerField(default=1)),
                ('defense', models.IntegerField(default=1)),
                ('health', models.IntegerField(default=1)),
                ('catched_at', models.DateTimeField(default=datetime.datetime(2023, 9, 26, 15, 12, 4, 910328))),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/')),
            ],
        ),
    ]
