# Generated by Django 4.2.5 on 2023-10-11 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_pokemon_created_by_alter_pokemon_catched_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='catched_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 15, 14, 14, 571458)),
        ),
    ]
