# Generated by Django 4.2.5 on 2023-10-03 21:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemons', '0010_alter_pokemon_catched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='catched_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 18, 45, 57, 542228)),
        ),
    ]
